version: "3.8"
services:
  nextjs-app:
    image: nextjs-app:latest
    ports:
      - "3000:3000"
    environment:
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
