/**
 * This code was generated by Builder.io
 */
import React from "react";
import { CalendarHeader } from "./CalendarHeader";
import { CalendarDays } from "./CalendarDays";

interface CalendarMonthProps {
  month: number;
  year: number;
  onDateClick: (date: Date) => void;
  selectedDate: Date | null;
}

export const CalendarMonth: React.FC<CalendarMonthProps> = ({
  month,
  year,
  onDateClick,
  selectedDate,
}) => {
  const monthName = new Date(year, month).toLocaleString("default", {
    month: "long",
  });

  return (
    <div className="flex overflow-hidden flex-col border-r border-solid border-r-zinc-300 min-w-[240px] w-[328px]">
      <div className="flex flex-col justify-center px-6 py-5 w-full max-md:px-5">
        <div className="flex flex-col w-full">
          <CalendarHeader monthName={monthName} year={year} />
          <CalendarDays
            month={month}
            year={year}
            onDateClick={onDateClick}
            selectedDate={selectedDate}
          />
        </div>
      </div>
    </div>
  );
};
