/**
 * This code was generated by Builder.io
 */
import React from "react";

interface CalendarHeaderProps {
  monthName: string;
  year: number;
}

export const CalendarHeader: React.FC<CalendarHeaderProps> = ({
  monthName,
  year,
}) => {
  return (
    <div className="flex gap-10 justify-between items-center w-full max-w-[280px]">
      <button
        className="flex overflow-hidden gap-2 justify-center items-center self-stretch p-2 my-auto rounded-lg"
        aria-label="Previous month"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/ae8059752f02d94bdb1c8744e08152e31cd9190e5c5738a3d21a15786da684ef?apiKey=27ce83af570848e9b22665bc31a03bc0&"
          alt=""
          className="object-contain self-stretch my-auto w-5 aspect-square"
        />
      </button>
      <div className="self-stretch my-auto text-base font-semibold text-center text-neutral-600">
        {monthName} {year}
      </div>
      <button
        className="flex overflow-hidden gap-2 justify-center items-center self-stretch p-2 my-auto rounded-lg"
        aria-label="Next month"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/d317746f5668ea4586ac1c1ef250131a1219b560ab0d9f6ab3576bcbe2402dd2?apiKey=27ce83af570848e9b22665bc31a03bc0&"
          alt=""
          className="object-contain self-stretch my-auto w-5 aspect-square"
        />
      </button>
    </div>
  );
};
