/**
 * This code was generated by Builder.io
 */
import React, { useState } from "react";
import { CalendarMonth } from "./CalendarMonth";
import { DatePickerFooter } from "./DatePickerFooter";

interface DatePickerProps {
  onDateSelect: (date: Date | null) => void;
}

export const DatePicker: React.FC<DatePickerProps> = ({ onDateSelect }) => {
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);

  const handleDateClick = (date: Date) => {
    setSelectedDate(date);
    onDateSelect(date);
  };

  const clearDate = () => {
    setSelectedDate(null);
    onDateSelect(null);
  };

  return (
    <div
      className="flex fixed top-2/4 left-2/4 items-start bg-white rounded-lg border border-solid shadow-xl -translate-x-2/4 -translate-y-2/4 border-zinc-100 z-[1000]"
      role="dialog"
      aria-label="Date Picker"
    >
      <div className="flex flex-col w-[656px] max-md:max-w-full">
        <div className="flex flex-wrap items-start max-md:max-w-full">
          <CalendarMonth
            month={10}
            year={2024}
            onDateClick={handleDateClick}
            selectedDate={selectedDate}
          />
          <CalendarMonth
            month={11}
            year={2024}
            onDateClick={handleDateClick}
            selectedDate={selectedDate}
          />
        </div>
        <DatePickerFooter
          selectedDate={selectedDate}
          onClear={clearDate}
          onApply={() => {}}
        />
      </div>
    </div>
  );
};
