/**
 * This code was generated by Builder.io
 */
import React from "react";

export const Header: React.FC = () => {
  return (
    <header>
      <div className="flex flex-wrap gap-1 justify-center items-center p-2 w-full text-base font-medium text-indigo-700 bg-indigo-50 max-md:max-w-full">
        <div className="self-stretch my-auto">
          You have <span className="font-semibold text-indigo-700">6</span> days
          left of your free trial!
        </div>
        <div className="gap-2 self-stretch my-auto underline decoration-auto decoration-solid underline-offset-auto">
          Upgrade here
        </div>
      </div>
      <nav className="flex flex-col gap-4 justify-center items-start px-6 py-4 w-full text-sm font-medium bg-white max-md:px-5 max-md:max-w-full">
        <div className="flex gap-4 items-center max-md:max-w-full">
          <button className="self-stretch px-4 py-2 my-auto text-white bg-indigo-700 rounded-lg w-[221px]">
            Company Profile
          </button>
          <button className="self-stretch px-4 py-2 my-auto whitespace-nowrap rounded-lg text-stone-500 w-[221px]">
            Files
          </button>
        </div>
      </nav>
    </header>
  );
};
