/**
 * This code was generated by Builder.io
 */
import React from "react";
import { NavItem } from "./NavItem";

const navItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/19d02f7ec1d4dd004a533622f4f55be643260fa14716660a4b48ab27b5be172e?apiKey=27ce83af570848e9b22665bc31a03bc0&",
    label: "Home",
    active: true,
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/501daf0f5e7ebe4b04690fdbdf683e377210318b121a880722a2e28a083d2683?apiKey=27ce83af570848e9b22665bc31a03bc0&",
    label: "My Tenders",
    active: false,
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/bb10bb3f541afe483518693a80f0246296ee88a9dc9972c8314c221c6ac7bf97?apiKey=27ce83af570848e9b22665bc31a03bc0&",
    label: "Profile",
    active: false,
  },
];

export const Sidebar: React.FC = () => {
  return (
    <aside className="flex fixed top-0 left-0 flex-col h-screen bg-indigo-700 min-w-[240px] w-[312px]">
      <div className="flex gap-10 justify-between px-6 py-4 w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/b076d6349980020e4d366e9fc2fd20689191596aa6b5a95042d7234934305016?apiKey=27ce83af570848e9b22665bc31a03bc0&"
          alt="Company logo"
          className="object-contain shrink-0 aspect-[3.09] w-[108px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/27ce83af570848e9b22665bc31a03bc0/ff95333ad0e3117d2d91da798dc69063004adaae58e73d5c088e39ad426c6411?apiKey=27ce83af570848e9b22665bc31a03bc0&"
          alt=""
          className="object-contain shrink-0 my-auto w-6 aspect-square"
        />
      </div>
      <nav className="flex overflow-auto flex-col flex-1 gap-2 px-4 pt-8 mt-6 text-base text-white border-t border-solid border-t-indigo-300">
        {navItems.map((item, index) => (
          <NavItem
            key={index}
            icon={item.icon}
            label={item.label}
            active={item.active}
          />
        ))}
      </nav>
    </aside>
  );
};
