/**
 * This code was generated by Builder.io
 */
import React from "react";
import { Sidebar } from "../shared/Sidebar";
import { SearchBar } from "./SearchBar";
import { FilterBar } from "./FilterBar";
import { TenderList } from "./TenderList";
import { Header } from "../shared/Header";
import { Tender } from "@/types/tender";
import { usePathname } from 'next/navigation';

interface TenderDashboardProps {
  tenders: Tender[];
  loading: boolean;
  error: string | null;
}

export const TenderDashboard: React.FC<TenderDashboardProps> = ({ tenders, loading, error }) => {
  const pathname = usePathname();
  const showDashboardControls = pathname === '/dashboard';

  return (
    <div className="flex overflow-hidden bg-white">
      <Sidebar />
      <main className="flex flex-col flex-1 ml-[312px] min-w-[240px] max-md:max-w-full">
        <Header userCreatedAt={new Date()} showNav={false} />
        <section className="flex flex-col justify-center p-6 w-full bg-white border-t border-b border-solid border-y-zinc-300 max-md:px-5 max-md:max-w-full">
          {showDashboardControls && (
            <>
              <SearchBar />
              <FilterBar />
            </>
          )}
        </section>
        <TenderList tenders={tenders} loading={loading} error={error} />
      </main>
    </div>
  );
};
