/**
 * This code was generated by Builder.io
 */
import React from "react";
import { TenderCard } from "./TenderCard";

const tenders = [
  {
    title: "Vehicle Fleet Management Services",
    description:
      "Invitation to tender for the provision of comprehensive vehicle fleet management services to support the efficient operation of its fleet. The services required include a variety of trucking fleet for commercial use.",
    match: 75,
    budget: "€8.500.000",
    country: "Ireland",
    countryFlag: "/flags/ireland.svg",
    lots: 4,
    status: "Open",
    posted: "November 7th, 2024",
    submissionDate: "November 17th, 2024",
    dueIn: "10 days",
  },
  {
    title: "Senior Care and Housing Support Officer",
    description:
      "Responsibilities include overseeing daily care needs, coordinating housing and social services, managing case files, and ensuring the residents' well-being and independence. The role requires strong communication skills, empathy, and a deep understanding of housing...",
    match: 55,
    budget: "€400.000",
    country: "France",
    countryFlag: "/flags/france.svg",
    lots: 3,
    status: "Open",
    posted: "November 7th, 2024",
    submissionDate: "November 19th, 2024",
    dueIn: "12 days",
  },
  {
    title: "IT Health Checks and Cyber Security Consultancy",
    description:
      "The chosen provider will be responsible for conducting comprehensive assessments of IT systems to identify vulnerabilities, ensuring compliance with security standards, and offering expert advice on cyber threat prevention. Key areas of focus include network security...",
    match: 85,
    budget: "€1.125.000",
    country: "Luxembourg",
    countryFlag: "/flags/luxembourg.svg",
    lots: 2,
    status: "Open",
    posted: "November 8th, 2024",
    submissionDate: "November 18th, 2024",
    dueIn: "10 days",
  },
];

export const TenderList: React.FC = () => {
  return (
    <div className="flex flex-col p-6 w-full max-md:px-5 max-md:max-w-full">
      {tenders.map((tender, index) => (
        <TenderCard key={index} tender={tender} />
      ))}
    </div>
  );
};
