/**
 * This code was generated by Builder.io
 */
import React from "react";
import { Sidebar } from "../shared/Sidebar";
import { SearchBar } from "./SearchBar";
import { FilterBar } from "./FilterBar";
import { TenderList } from "./TenderList";
import { Header } from "../shared/Header";

export const TenderDashboard: React.FC = () => {
  return (
    <div className="flex overflow-hidden bg-white">
      <Sidebar />
      <main className="flex flex-col flex-1 ml-[312px] min-w-[240px] max-md:max-w-full">
        <Header userCreatedAt={new Date()} showNav={false} />
        <section className="flex flex-col justify-center p-6 w-full bg-white border-t border-b border-solid border-y-zinc-300 max-md:px-5 max-md:max-w-full">
          <SearchBar />
          <FilterBar />
        </section>
        <TenderList />
      </main>
    </div>
  );
};
