/**
 * This code was generated by Builder.io
 */
import React from "react";

export const TrialBanner: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-1 justify-center items-center p-2 w-full text-base font-medium text-indigo-700 bg-indigo-50 max-md:max-w-full">
      <div className="self-stretch my-auto">
        You have <span className="font-semibold text-indigo-700">6</span> days
        left of your free trial!
      </div>
      <a
        href="#upgrade"
        className="gap-2 self-stretch my-auto underline decoration-auto decoration-solid underline-offset-auto"
      >
        Upgrade here
      </a>
    </div>
  );
};
